apiVersion: v1
kind: Pod
metadata:
  name: multi-container-volume-pod
spec:
  # Define an emptyDir volume
  volumes:
  - name: shared-data
    emptyDir: {}
  # Pod containers
  containers:
  - name: container1
    image: alpine:3.12.0
    command: [ "/bin/sh", "-c", "sleep infinity; mkdir /etc/a/data; cd /etc/a/data; echo 'Hello World' > hello.txt" ]
    # Mount the volume at /etc/a
    volumeMounts:
    - name: shared-data
      mountPath: /etc/a
  - name: container2
    image: alpine:3.12.0
    command: [ "/bin/sh", "-c", "sleep infinity; sh -c 'ls /etc/b/data/hello.txt'" ]
    # Mount the volume at /etc/b
    volumeMounts:
    - name: shared-data
      mountPath: /etc/b